// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
)

// InitializeContainer creates a new application container with all dependencies
func InitializeContainer() (*Container, error) {
	wire.Build(
		ProviderSet,
		NewContainer,
	)
	return nil, nil
} 