// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/BarneyRubble12/specdrill/internal/core/executor"
	"github.com/BarneyRubble12/specdrill/internal/core/parser"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeContainer creates a new application container with all dependencies
func InitializeContainer() (*Container, error) {
	parserParser := parser.NewParser()
	executorExecutor := executor.NewExecutor()
	container := NewContainer(parserParser, executorExecutor)
	return container, nil
}

// wire.go:

// ProviderSet is a Wire provider set for the application
var ProviderSet = wire.NewSet(parser.NewParser, executor.NewExecutor)
